// <auto-generated />
using System;
using Filmovi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filmovi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509201311_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Filmovi.Api.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraFilma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Filmovi");
                });

            modelBuilder.Entity("Filmovi.Api.Models.Kino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kina");
                });

            modelBuilder.Entity("Filmovi.Api.Models.KinoFilm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CijenaKarte")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumProjekcije")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("KinoId");

                    b.ToTable("KinoFilmovi");
                });

            modelBuilder.Entity("Filmovi.Api.Models.KinoFilm", b =>
                {
                    b.HasOne("Filmovi.Api.Models.Film", "Film")
                        .WithMany("KinoFilmovi")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Filmovi.Api.Models.Kino", "Kino")
                        .WithMany("KinoFilmovi")
                        .HasForeignKey("KinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Kino");
                });

            modelBuilder.Entity("Filmovi.Api.Models.Film", b =>
                {
                    b.Navigation("KinoFilmovi");
                });

            modelBuilder.Entity("Filmovi.Api.Models.Kino", b =>
                {
                    b.Navigation("KinoFilmovi");
                });
#pragma warning restore 612, 618
        }
    }
}
